# Generated by Django 3.2.5 on 2021-07-28 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='name')),
                ('height', models.CharField(max_length=24, verbose_name='height')),
                ('homeworld', models.CharField(max_length=24, verbose_name='homeworld')),
                ('films', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=240, verbose_name='films'), size=8)),
                ('url', models.CharField(max_length=240, verbose_name='url')),
            ],
            options={
                'db_table': 'characters',
            },
        ),
    ]
